version: 2.1

executors:
  docker-executor:
    docker:
      - image: ubuntu:20.04  # Usar una imagen base de Ubuntu para que se pueda usar apt-get
    working_directory: ~/workspace

jobs:
  build:
    docker:
      - image: ubuntu:20.04  # Usar una imagen base de Ubuntu para que se pueda usar apt-get
    steps:
      - checkout  # Hacer checkout del código fuente
      - run:
          name: Install Docker
          command: |
            apt-get update && apt-get install -y docker.io  # Instalar Docker usando apt-get
      - run:
          name: Construir la imagen Docker personalizada
          command: |
            docker build -t diegobarba/mi-imagen:latest .

  mysql:
    docker:
      - image: mysql:5.7  # Utilizar la imagen oficial de MySQL
    steps:
      - run:
          name: Levantar contenedor MySQL
          command: |
            docker run --name mysql -e MYSQL_ROOT_PASSWORD=123456 -d -p 3306:3306 mysql:5.7
      - run:
          name: Esperar a que MySQL esté listo
          command: |
            # Esperar a que MySQL esté listo antes de ejecutar las pruebas
            until docker exec mysql mysqladmin --user=root --password=123456 --host="localhost" --port=3306 ping --silent; do
              echo "Esperando a que MySQL esté listo..."
              sleep 5
            done
      - run:
          name: Ejecutar pruebas con la imagen creada
          command: |
            docker run --rm --link mysql:db diegobarba/mi-imagen:latest

  push:
    docker:
      - image: ubuntu:20.04  # Usar Ubuntu también para el push, por consistencia
    steps:
      - checkout
      - run:
          name: Subir la imagen a Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  # Usa las variables de entorno de CircleCI
            docker push diegobarba/mi-imagen:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - mysql:
          requires:
            - build
      - push:
          requires:
            - mysql
