version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:23.0.1  # Imagen base con Java
      - image: cimg/mysql:8.0
        environment:
          #MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: calidad
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd


    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
            


      - run:
          name: Configurar base de datos
          command: |
            echo "Creando base de datos para pruebas..."
            mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE calidad;"      
      
      
      - run:
          name: Compilar proyecto y ejecutar pruebas
          #command: mvn test -Dtest=com.mayab..quality.unittest.UserServiceTest,com.mayab..quality.integration.UserServiceTest


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
