version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:23.0.1  # Imagen base con Java
      - image: mysql:5.7            # Imagen de MySQL como servicio
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calidad

    steps:
      - checkout
      
      - run:
          name: Instalar cliente MySQL
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
      
      - run:
          name: Esperar a que MySQL esté listo
          command: |
            until mysqladmin ping --host=mysql --user=root --password=root --silent; do
              echo "Esperando a que MySQL esté listo..."
              sleep 5
            done
      
      - run:
          name: Compilar proyecto y ejecutar pruebas
          command: mvn clean install && mvn test -Dtest=UserDAOTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
