version: 2.1

jobs:
  build_and_test:
    docker:
      - image: maven:3.8.5-openjdk-17  # Imagen base con Java
    steps:
      - checkout
      - run:
          name: Instalar dependencias (MySQL y Chrome)
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-server google-chrome-stable

      - run:
          name: Iniciar MySQL
          command: sudo service mysql start
      
      - run:
          name: Crear base de datos
          command: |
            mysql -e "CREATE DATABASE calidad;" -u root

      - run:
          name: Esperar a que MySQL esté listo
          command: |
            until mysqladmin ping --host=localhost --port=3306 --user=root --silent; do
              echo "Esperando a que MySQL esté listo..."
              sleep 5
            done
      
      - run:
          name: Compilar proyecto y ejecutar pruebas
          command: mvn clean install && mvn test -Dtest=UserDAOTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test

