version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:23.0.1  # Imagen base con Java
      - image: mysql:8.0            # Imagen de MySQL como servicio
      - image: selenium/standalone-chrome
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calidad

    steps:
      - checkout


      - run:
          name: Configurar base de datos
          command: |
            echo "Creando base de datos para pruebas..."
            mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE calidad;"
      
      
      - run:
          name: Instalar cliente MySQL
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
      
      
      
      - run:
          name: Compilar proyecto y ejecutar pruebas
          command: mvn test -Dtest=com.mayab..quality.unittest.UserServiceTest,com.mayab..quality.functional.SeleniumTests


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
